name: <meta>
description: The `<meta>` element represents metadata used by the browser or search engines about the page including description, keywords, character sets, etc.
spec: https://html.spec.whatwg.org/multipage/semantics.html#meta
group: html
compat_features:
  - api.HTMLMetaElement
  - api.HTMLMetaElement.content
  - api.HTMLMetaElement.httpEquiv
  - api.HTMLMetaElement.media
  - api.HTMLMetaElement.name
  - html.elements.meta
  - html.elements.meta.charset
  - html.elements.meta.content
  - html.elements.meta.http-equiv
  # Excluded because of a non-real value
  # - html.elements.meta.http-equiv.content-type
  - html.elements.meta.http-equiv.refresh
  - html.elements.meta.name
  - html.elements.meta.name.color-scheme
  - html.elements.meta.name.referrer
  - html.elements.meta.name.theme-color
